print("hello i'am naisa")
print("Today i'am going to talk about Ramadan")
print("in ramadan i wakeup for sehri at 3:30AM")
print("then after sehri i sleep at 4:00AM")
print("then at morning i usually wakeup at 10:30AM")
print("After wakeup i play with my younger sister")
print("my home tutor comes at 12:30PM")
print("then my home tutor comes, then i study for 1 hour")
print("and after that i take a nap at 3:30PM")
print("then after waking up i help my mom for making iftar")
